#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "windows.h"
#include "time.h"


int main()
{
	system("chcp 936&title 第十五例 C语言生成多语言恋人生日祝福&color e&cls");
	time_t t=time(nullptr);//使用time_t机构体，包含在time.h文件头中。
	struct tm lt;
	time(&t);//获取Unix时间戳。    
	localtime_s(&lt,&t);//转为时间结构。    
	//printf("%d年%d月%d日 %d:%d:%d\n", lt.tm_year + 1900, lt.tm_mon, lt.tm_mday, lt.tm_hour, lt.tm_min, lt.tm_sec);
	char yt1[1000] = "echo print(\"            *****************************     得 天    ***    ", yt2[10] = { 0 }, yt3[50] = "年      ****\")>>D:\\HappyBirthday.py";
	_itoa_s(lt.tm_year + 1900, yt2, 10);
	strcat_s(yt1, yt2);
	strcat_s(yt1, yt3);
	char yt4[1000] = "echo print(\"           **            ***                     开    ***       ", yt5[5] = { 0 }, yt6[5] = "月", yt7[5] = { 0 }, yt8[50] = "日 ****\")>>D:\\HappyBirthday.py";
	_itoa_s(lt.tm_mon, yt5, 10);
	_itoa_s(lt.tm_mday, yt7, 10);
	strcat_s(yt4, yt5);
	strcat_s(yt4, yt6);
	strcat_s(yt4, yt7);
	strcat_s(yt4, yt8);
	system("mshta vbscript:msgbox(\"亲爱的，生日快乐！\"^&vbCrLf^&\"请点击“确定”，开启一段奇妙的旅程。\",64,\"生日快乐！\")(window.close)");
	system("start \"\" mshta vbscript:CreateObject(\"Shell.Application\").ToggleDesktop");
	Sleep(1000);
	system("taskkill /im mshta.exe /f>nul&cls");
	system("echo #coding=gbk>D:\\HappyBirthday.py");
	system("echo import os>>D:\\HappyBirthday.py");
	system("echo import random>>D:\\HappyBirthday.py");
	system("echo import time>>D:\\HappyBirthday.py");
	system("echo os.system(\"title 祝生日快乐！&cls\")>>D:\\HappyBirthday.py");
	system("echo print(\"\\n\")>>D:\\HappyBirthday.py");
	system("echo print(\"                         ***                           ***********************\")>>D:\\HappyBirthday.py");
	system("echo print(\"                         ***                  一       ***********************\")>>D:\\HappyBirthday.py");
	system("echo print(\"               **        ***    加油鸭！      定       ***                ****\")>>D:\\HappyBirthday.py");
	system("echo print(\"              **         ***                  要       ***    又大一岁    ****\")>>D:\\HappyBirthday.py");
	system("echo print(\"             ***************************      记 天    ***                ****\")>>D:\\HappyBirthday.py");
	system(yt1);
	system(yt4);
	system("echo print(\"          **             ***       OK  成功啦！  开    ***********************\")>>D:\\HappyBirthday.py");
	system("echo print(\"                冲       ***                     心    ***********************\")>>D:\\HappyBirthday.py");
	system("echo print(\"            冲      *************                心    ***                ****\")>>D:\\HappyBirthday.py");
	system("echo print(\"        冲          *************                快    ***     快乐哦！   ****\")>>D:\\HappyBirthday.py");
	system("echo print(\"    冲                   ***                     快    ***                ****\")>>D:\\HappyBirthday.py");
	system("echo print(\"            尸位素餐     ***     居心不安        乐    ***   哈哈哈哈哈   ****\")>>D:\\HappyBirthday.py");
	system("echo print(\"                         ***                     乐    ***                ****\")>>D:\\HappyBirthday.py");
	system("echo print(\"       ****************************************        ***********************\")>>D:\\HappyBirthday.py");
	system("echo print(\"      ******************************************       ***********************\")>>D:\\HappyBirthday.py");
	system("echo print(\"\")>>D:\\HappyBirthday.py");
	system("echo print(\"\")>>D:\\HappyBirthday.py");
	system("echo print(\"\")>>D:\\HappyBirthday.py");
	system("echo print(\"=\"*88)>>D:\\HappyBirthday.py");
	system("echo print(\"=\"*88)>>D:\\HappyBirthday.py");
	system("echo print(\"\")>>D:\\HappyBirthday.py");
	system("echo print(\"\")>>D:\\HappyBirthday.py");
	system("echo print(\"点击窗口右上角关闭按钮关闭本窗口，去往cmd的世界，而每一个vbs弹窗，都是一个个微小的vbs世界。\")>>D:\\HappyBirthday.py");
	system("echo color=\"1234567890abcdef\">>D:\\HappyBirthday.py");
	system("echo while True:>>D:\\HappyBirthday.py");
	system("echo 	i=random.randint(0,15)>>D:\\HappyBirthday.py");
	system("echo 	j=random.randint(0,15)>>D:\\HappyBirthday.py");
	system("echo 	if i!=j:>>D:\\HappyBirthday.py");
	system("echo 		do=\"color \"+color[i]+color[j]>>D:\\HappyBirthday.py");
	system("echo 		os.system(do)>>D:\\HappyBirthday.py");
	system("echo 		time.sleep(2)>>D:\\HappyBirthday.py");
	system("mshta vbscript:msgbox(\"欢迎来到python世界！\"^&vbCrLf^&\"小小的python将会为您展示色彩不同的生日祝福哟！\"^&vbCrLf^&\"如果看腻了，别忘了点击右上角关闭按钮去往下一个世界哦！\",64,\"生日快乐！\")(window.close)");
	system("start /low \"\" mshta vbscript:msgbox(\"预备\",0,\"倒计时\")(window.close)"); 
	Sleep(1000);
	system("taskkill /im mshta.exe /f>nul&cls"); 
	system("start /low \"\" mshta vbscript:msgbox(\"3\",0,\"倒计时\")(window.close)");
	Sleep(1000);
	system("taskkill /im mshta.exe /f>nul&cls");
	system("start /low \"\" mshta vbscript:msgbox(\"2\",0,\"倒计时\")(window.close)");
	Sleep(1000); 
	system("taskkill /im mshta.exe /f>nul&cls");
	system("start /low \"\" mshta vbscript:msgbox(\"1\",0,\"倒计时\")(window.close)");
	Sleep(1000); 
	system("taskkill /im mshta.exe /f>nul&cls");
	system("start /realtime /wait \"\" D:\\HappyBirthday.py");
	system("del /a /f /q D:\\HappyBirthday.py");
	system("mshta vbscript:msgbox(\"欢迎来到cmd世界！\"^&vbCrLf^&\"我虽卑微，却无所不能。\"^&vbCrLf^&\"若要返回C语言世界，请让在任务栏等你的我带你返回。\",64,\"生日快乐！\")(window.close)");
	system("start /low \"\" mshta vbscript:msgbox(\"错误：无法启动，原因：你太可爱了。\"^&vbCrLf^&\"哈哈哈哈，开个玩笑而已。\"^&vbCrLf^&\"别着急，待会会弹出cmd。\",16,\"生日快乐！\")(window.close)");
	system("echo Windows Registry Editor Version 5.00>D:\\HappyBirthday.reg");
	system("echo.>>D:\\HappyBirthday.reg");
	system("echo [HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon]>>D:\\HappyBirthday.reg"); 
	system("echo \"LegalNoticeCaption\"=\"亲爱的：祝你生日快乐——\">>D:\\HappyBirthday.reg");
	system("echo \"LegalNoticeText\"=\"你开开心心过好每一天，就是我最大的心愿。\">>D:\\HappyBirthday.reg"); 
	system("echo.>>D:\\HappyBirthday.reg");
	system("echo [HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run]>>D:\\HappyBirthday.reg");
	system("echo \"HappyBirthday\"=\"D:\\\\HappyBirthday.reg\">>D:\\HappyBirthday.reg");
	system("echo @echo off>D:\\HappyBirthday.bat");
	system("echo title 生日快乐！（点击右侧关闭按钮可关闭骚话窗口，记得返回找任务栏上的C程序哦！）>>D:\\HappyBirthday.bat");
	system("echo color e>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :main>>D:\\HappyBirthday.bat");
	system("echo cls>>D:\\HappyBirthday.bat");
	system("echo echo 我有很多骚话想要对你说，请输入一个40以内的序号：>>D:\\HappyBirthday.bat");
	system("echo set /p n=>>D:\\HappyBirthday.bat");
	system("echo goto ^%n^%A>>D:\\HappyBirthday.bat");
	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :1A>>D:\\HappyBirthday.bat");
	system("echo echo 你在我的心中扎根，我们的友谊露重更深；你在我的牵挂中缤纷，我们的情感喜大普奔；你在我的坦诚中光临，我们的心有灵犀更近；你在我的问候中欢欣，我们的关爱情不自禁；你在我的祝福中兴奋，祝你生日快乐开心！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat"); 
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :2A>>D:\\HappyBirthday.bat");
	system("echo echo 好友如梦似幻，日夜兼程思念，亲朋血脉相连，话语滋润心田，知音一生有缘，牵手幸福永远，挚爱看雨听蝉，开心快乐无边，知己晓得冷暖，经常相互惦念，我心与你相牵，送你灿烂心愿，祝你生日圆满，谱写壮丽诗篇！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :3A>>D:\\HappyBirthday.bat");
	system("echo echo 一捧香土藏奇葩，孕育种子发新芽，寄托情思千万里，一年四季绘新画；一滴细雨催鲜花，雨过天晴景色佳，朵朵相思满枝桠，千丝万缕放光华；数条微信给你发，祝你开心美潇洒，生日快乐伴随你，高枕无忧爱融洽！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :4A>>D:\\HappyBirthday.bat");
	system("echo echo 有山有水有风景，景色绚丽心放松，有意有爱有真情，情义无价爱与共，有风有雨有天空，天空晴朗任你行，有聚有缘有宾朋，亲友挚爱化寒冰，有来有往有憧憬，前程似锦美梦成，祝你生日最高兴，时刻都有新感动！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :5A>>D:\\HappyBirthday.bat");
	system("echo echo 意外的温暖，意外的感动，意外的关怀，意外的欣赏，意外的珍视，意外的美好。意外，其实不是意外；意外，其实是一种必然。我用温暖的微笑问候你，用如水的柔情拥抱你，用纯朴的真心陪伴你，用无瑕的美丽祝福你：亲爱的，生日快乐，一生幸福！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :6A>>D:\\HappyBirthday.bat");
	system("echo echo 看花的娇艳，思念着你的容颜，望流云飘逸，惦记着你的佳期，轻轻地屏住呼吸，距离太远还是无法感受到你，可祝福与你形影不离，在你的生日到来之际，诚挚地献上我的三个祝愿：一愿你身体健康；二愿你幸福快乐；三愿你万事如意，笑容美丽！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :7A>>D:\\HappyBirthday.bat");
	system("echo echo 多年前的今天有颗流星的划落，带着一位天使来到人间做客！多么幸运在大学重新遇见你，带来那么多的快乐、阳光与美好，你是那么纯真，那么善良。亲爱的，祝你生日快乐！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :8A>>D:\\HappyBirthday.bat");
	system("echo echo 如果说，珠穆朗玛峰代表一个高度，桃花潭水代表一个深度，婵娟嫦娥代表一个美度，观音菩萨代表一个吉祥福度。那我说，你今生的平安好运幸福快乐就是我用心祝福的长度。特别的祝福给特别的你，祝你生日快乐好心情，一生幸福乐悠悠。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :9A>>D:\\HappyBirthday.bat");
	system("echo echo 今天，送你365个快乐，愿你每天都有快乐生活；今天，送你365个幸福，愿你每天都有幸福守护；今天，送你365个梦想，愿你每天都有梦想希望；今天，送你365句吉言，愿你每天都有好运陪伴：，生日快乐，一生平安！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :10A>>D:\\HappyBirthday.bat");
	system("echo echo 喜鹊早已跳上了枝头，唱起幸福的旋律。鱼儿早已在水底徜徉，吐着祝福的气泡。我把幸福的花朵缠上平安的丝带，让健康的绿荫爬满你的生活，使美好的日子永恒。我把祝福用光芒串上，让太阳的辉煌照亮你的角角落落，祝你生日快乐！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :11A>>D:\\HappyBirthday.bat");
	system("echo echo 春天的鲜花，夏天的浪花，秋天的繁华，冬天的雪花，不论何时何地都希望你乐开花，朋友，在这阳光明媚的日子，我为你放飞一群祝福，祝你生日快乐，愿你生活幸福，笑语轻扬。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :12A>>D:\\HappyBirthday.bat");
	system("echo echo 也许是时空茫然，注定的事情发生在注定的时空之中。不约而同间，我与你在大学重逢，是天意，抑或是人为？>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :13A>>D:\\HappyBirthday.bat");
	system("echo echo 别太晚睡呀！睡太晚对身体不好，尤其是你这种长得那么讨人喜爱的。早点休息，明天见！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :14A>>D:\\HappyBirthday.bat");
	system("echo echo 留不住的是时间，带不走的是思念，忘不了的是情谊，斩不断的是祝福。每年都有一个特别的日子，从此以后，每年都有我最真诚的祝福：生日快乐，我的朋友——。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :15A>>D:\\HappyBirthday.bat");
	system("echo echo 在你生日的今天，我用友谊的钢琴，伴着和谐的生日祝福，轻轻地弹奏快乐的音符，化就世间最美的协作奏明曲，作为礼物送给你——愿你的明天更加美好！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :16A>>D:\\HappyBirthday.bat");
	system("echo echo “打字打得快有什么用，打得准才行。”然后，我就十分十分成功地被你的眼神杀死了。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :17A>>D:\\HappyBirthday.bat");
	system("echo echo 总有一天，你会把我折磨死；总有一天，你会远远超越我。加油鸭，冲冲冲！！！>>D:\\HappyBirthday.bat");
	system("echo echo P.S. 不过，死在你手里应该也是一件挺幸福的事情吧！？>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :18A>>D:\\HappyBirthday.bat");
	system("echo echo 天涯海角，总有一份思念属于你。四面八方，总有一丝牵挂缠绕你。不管你身在何方，我都送上最美的祝福。任时光流逝，任岁月蹉跎。诚祝：生日快乐，天天快乐！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :19A>>D:\\HappyBirthday.bat");
	system("echo echo 有一个特别的日子，鲜花都为你展现；有一个特殊的日期，阳光都为你温暖；有一个美好的时刻，百灵都为你欢颜；有一个难忘的今天，亲朋好友都为你祝愿；那就是今天，你的生日，祝你幸福安康顺意连年！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :20A>>D:\\HappyBirthday.bat");
	system("echo echo 年年岁岁花相似，我依然记得这个特殊的日子；岁岁年年人不同，我依旧改变不了对你的深情；弹指挥间近咫尺，我再忙碌也不能淡忘你的生日；转眼一年与君行，希望你今年的生日能与往年有所不同。祝你生日快乐，你的颜容一年四季鲜花伴美景！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :21A>>D:\\HappyBirthday.bat");
	system("echo echo 心情只要快乐，风风雨雨，亦觉阳光明媚；心态只要平和，坎坎坷坷，亦觉幸福无限；怀着美好的信念，怀着幸福的憧憬，幸福就在你我的身边。生日来临之际，愿你读懂幸福，享受美好！祝：生日快乐!>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :22A>>D:\\HappyBirthday.bat");
	system("echo echo 许你一个美好的明天，愿世间的每一个角落都洒满璀璨的星光！祝愿也坚信您，前程似锦。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :23A>>D:\\HappyBirthday.bat");
	system("echo echo 生命不在于长短，精彩十分重要。生活不在于富裕，健康才是王道。情谊不在于亲密无间，真心在乎就好。生日不在于吃啥喝啥送啥，只要有问候祝福就好。生日快乐，天天快乐，愿幸福快乐从此绵延一直到老！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :24A>>D:\\HappyBirthday.bat");
	system("echo echo 愿一道道记忆归结为记印，化就一道道瑰丽无比的遥感，永恒于星空之下。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :25A>>D:\\HappyBirthday.bat");
	system("echo echo 太阳是金色的，月亮是银色的，你的生日是彩色的，愿你被幸福环绕，被好运追逐，被快乐降伏，被笑容粘住。那时别忘了，有人“远在天边，近在眼前”，为你祝福，与你一同分享快乐！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :26A>>D:\\HappyBirthday.bat");
	system("echo echo 你的音乐悟性那么高，什么时候我才能给你开始第一节钢琴课呢？[捂脸][捂脸][捂脸]>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :27A>>D:\\HappyBirthday.bat");
	system("echo echo 当你累了时候，别忘了还有我这个小你两个星期的弟弟，永远在默默地支持你。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :28A>>D:\\HappyBirthday.bat");
	system("echo echo 生日快乐！祝你身体健康、四季平安、天天快乐、学业进步、“猪”事顺利、心想事成、万事如意！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :29A>>D:\\HappyBirthday.bat");
	system("echo echo 啥时候你愿与我结婚，我会用最动情的手法，用最真挚的情感，演奏《瓦格纳婚礼进行曲》。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :30A>>D:\\HappyBirthday.bat");
	system("echo echo 尸位素餐，居心不安。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :31A>>D:\\HappyBirthday.bat");
	system("echo echo 我有点想听你唱《天空之城》，怎么办？>>D:\\HappyBirthday.bat");
	system("echo echo P.S..不要告诉我“凉拌”。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :32A>>D:\\HappyBirthday.bat");
	system("echo echo 我曾经答应过你我每天要睡八小时，可是我发现，没有你的约束，我好像执行不了。。。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :33A>>D:\\HappyBirthday.bat");
	system("echo echo 人说，星空啊，深邃、静谧、净化、清幽；我曰，亲爱的，沉稳、慎独、成熟、善良。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :34A>>D:\\HappyBirthday.bat");
	system("echo echo Wish you a fairly happy tomorrow^! May you an exceedingly better future^!>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :35A>>D:\\HappyBirthday.bat");
	system("echo echo 你在我的心中扎根，我们的友谊露重更深；你在我的牵挂中缤纷，我们的情感喜大普奔；你在我的坦诚中光临，我们的心有灵犀更近；你在我的问候中欢欣，我们的关爱情不自禁；你在我的祝福中兴奋，祝你生日快乐开心！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :36A>>D:\\HappyBirthday.bat");
	system("echo echo 现在是北京时间：^%date^% ^%time^%，我们的爱情必将99。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :37A>>D:\\HappyBirthday.bat");
	system("echo echo 话说有时候我真的很想打你，但是我觉得我不是你的对手。>>D:\\HappyBirthday.bat");
	system("echo echo “我”尝试撤回上一条消息，已成功被对方阻止。>>D:\\HappyBirthday.bat");
	system("echo echo 抱歉，我刚才好像说错话了，你打我吧！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :38A>>D:\\HappyBirthday.bat");
	system("echo echo 我把我的人身控制权交给你啦！你一定要好好保管哦！别把我弄丢了哈。哪天你把我人生控制权也拿走了，我会很开心的。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :39A>>D:\\HappyBirthday.bat");
	system("echo echo 我还欠你n顿宵夜呢！你什么时候有空约我呗，我随时待命。>>D:\\HappyBirthday.bat");
	system("echo echo P.S..n趋于∞。>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
;	system("echo.>>D:\\HappyBirthday.bat");
	system("echo :40A>>D:\\HappyBirthday.bat");
	system("echo echo 一个小小的cmd，承载不了我心中的所有话语，谨单纯地祝愿你，生日快乐，天天开心！>>D:\\HappyBirthday.bat");
	system("echo pause>>D:\\HappyBirthday.bat");
	system("echo goto main>>D:\\HappyBirthday.bat");
	system("taskkill /im mshta.exe /f>nul&cls");
	system("start /realtime /wait \"\" cmd /c D:\\HappyBirthday.bat");
	system("start /realtime \"\" mshta vbscript:msgbox(\"请单击在任务栏上安静等待你许久的我。\",64,\"生日快乐！\")(window.close)");
	system("color e&cls");
	printf("欢迎返回C语言世界，请按任意键继续。\n");
	system("pause>nul&taskkill /im mshta.exe /f>nul&cls");
	int i, j;
	for (i = 1; i <= 120; i += 1)
	{
		for (j = 1; j <= i; j++)
			printf("*");
		printf("\n");
		Sleep(50);
	}
	for (i = 119; i >= 1; i -= 1)
	{
		for (j = 1; j <= i; j++)
			printf("*");
		printf("\n");
		Sleep(50);
	}
	system("del /a /f /q D:\\HappyBirthday.bat>nul&cls");
	system("mshta vbscript:msgbox(\"接下来会弹出一个资源管理器窗口，双击运行，这是一个彩蛋。\",64,\"生日快乐！\")(window.close)");
	system("start /realtime \"\" \"D:\\\"");
	Sleep(1000); 
	system("mshta vbscript:CreateObject(\"Wscript.Shell\").AppActivate(\"D:\\ \")(window.close)");
	Sleep(500);
	system("mshta vbscript:CreateObject(\"Wscript.Shell\").SendKeys(\"{H},{a},{p},{p},{y},{B},{i},{r},{t},{h},{d},{a},{y}\")(window.close)");
	printf("请双击HappyBirthday.reg导入彩蛋，导入完成后，请按任意键继续。");
	system("pause>nul");
	system("echo Windows Registry Editor Version 5.00>D:\\HappyBirthday.reg");
	system("echo.>>D:\\HappyBirthday.reg"); 
	system("echo [HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon]>>D:\\HappyBirthday.reg");
	system("echo \"LegalNoticeCaption\"=\"\">>D:\\HappyBirthday.reg");
	system("echo \"LegalNoticeText\"=\"\">>D:\\HappyBirthday.reg");
	system("echo.>>D:\\HappyBirthday.reg");
	system("echo [-HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\\HappyBirthday]>>D:\\HappyBirthday.reg");
	system("cls");
	Sleep(1000);
	printf("\n感谢有你，感怀遇见，祝：生日快乐！天天快乐！\n\n\nThis is the end of this program. Thank you very much!");
	system("pause>nul&cls");
	return 0;
}